import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/cartcontext";
import { UserProvider } from "./context/usercontext";
import Script from "next/script";
// import FluidSimulation from "@/component/FluidSimulation/FluidSimulation";
import { Toaster } from "react-hot-toast";
import QueryProvider from "./QueryProvider";
import Chat from "@/component/chat/chat";
import { ChatProvider } from "./context/chat.context";
import ClientLayout from "./ClientLayout";
import FluidSimulations from "@/components/ui/FluidSimulation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <Script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js'  strategy="beforeInteractive"></Script>
      </head>
      <body
        className={`${geistSans.variable} font-sans bg-[var(--background)] text-[var(--foreground)] dark:bg-[var(--background)]`}
       >
        <QueryProvider>
        <UserProvider>
        <CartProvider>
        <ChatProvider>
          <FluidSimulations/>
        <ClientLayout>{children}</ClientLayout>
        <Toaster position="top-right" reverseOrder={false} />
        </ChatProvider>
        </CartProvider>
        </UserProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
